from whoosh import fields

SCHEMA = fields.Schema(
    faq_id=fields.ID(stored=True, unique=True),
    idioma=fields.KEYWORD(stored=True),
    intencion=fields.KEYWORD(stored=True),
    pregunta=fields.TEXT(stored=True),
    respuesta=fields.STORED,
)

FAQS_DEMO = [
    {'faq_id': '1',  'idioma': 'es', 'intencion': 'recipe',
     'pregunta': 'como hacer pollo al horno',
     'respuesta': 'Precalienta el horno a 200°C, sazona el pollo con sal, pimienta y aceite, y hornéalo 45 min.'},
    {'faq_id': '2',  'idioma': 'es', 'intencion': 'recipe',
     'pregunta': 'como hacer pasta al dente',
     'respuesta': 'Hierve agua con sal abundante, añade la pasta y cocínala el tiempo indicado en el paquete.'},
    {'faq_id': '3',  'idioma': 'es', 'intencion': 'cook_time',
     'pregunta': 'cuanto tiempo tarda el pollo al horno',
     'respuesta': 'El pollo entero tarda unos 20 min por cada 500g a 180°C (pechuga: 25-30 min a 200°C).'},
    {'faq_id': '4',  'idioma': 'es', 'intencion': 'cook_time',
     'pregunta': 'cuanto tiempo se hierve el arroz',
     'respuesta': 'El arroz blanco se hierve 18-20 min a fuego medio con tapa y proporción 1:2 (arroz:agua).'},
    {'faq_id': '5',  'idioma': 'es', 'intencion': 'ingredient_substitution',
     'pregunta': 'puedo sustituir mantequilla por aceite',
     'respuesta': 'Sí, usa 3/4 de la cantidad en aceite vegetal neutro (girasol o maíz) en lugar de mantequilla.'},
    {'faq_id': '6',  'idioma': 'es', 'intencion': 'nutrition_info',
     'pregunta': 'cuantas calorias tiene el pollo',
     'respuesta': 'El pollo cocido sin piel tiene aprox. 165 kcal por 100g; el muslo con piel asciende a 215 kcal.'},
    {'faq_id': '7',  'idioma': 'es', 'intencion': 'calories',
     'pregunta': 'cuantas calorias tiene la pasta',
     'respuesta': 'La pasta cocida tiene aprox. 131 kcal por 100g; la pasta seca, unos 350 kcal por 100g.'},
    {'faq_id': '8',  'idioma': 'es', 'intencion': 'food_last',
     'pregunta': 'cuanto tiempo dura el queso en la nevera',
     'respuesta': 'Los quesos curados duran 3-4 semanas en nevera; los frescos, 5-7 días tras su apertura.'},
    # English equivalents
    {'faq_id': '9',  'idioma': 'en', 'intencion': 'recipe',
     'pregunta': 'how to make baked chicken',
     'respuesta': 'Preheat oven to 400°F, season chicken with salt, pepper and oil, and bake for 45 min.'},
    {'faq_id': '10', 'idioma': 'en', 'intencion': 'recipe',
     'pregunta': 'how to cook pasta al dente',
     'respuesta': 'Boil salted water, add pasta and cook for the time stated on the package.'},
    {'faq_id': '11', 'idioma': 'en', 'intencion': 'cook_time',
     'pregunta': 'how long does chicken take in the oven',
     'respuesta': 'A whole chicken takes about 20 min per 500g at 375°F (breast: 25-30 min at 400°F).'},
    {'faq_id': '12', 'idioma': 'en', 'intencion': 'cook_time',
     'pregunta': 'how long do you boil rice',
     'respuesta': 'White rice simmers for 18-20 min covered on medium heat with a 1:2 rice-to-water ratio.'},
]
